name: generate breakout svg

on:
  schedule:
    - cron: "0 */24 * * *" # runs every day
  workflow_dispatch:       # allows manual run

jobs:
  generate-svg:
    permissions:
      contents: write
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: generate SVG
        uses: cyprieng/github-breakout@v1
        with:
          github_username: ${{ github.repository_owner }}
          github_token: ${{ secrets.GITHUB_TOKEN }}   # ensure token is available
          enable_ghost_bricks: false                 
           paddle_color: "#40c463" 
          ball_color: "#216e39"   
          bricks_colors: "#ebedf0,#9be9a8,#40c463,#30a14e,#216e39"

      - name: Move generated SVGs to temp
        run: |
          mkdir -p /tmp/breakout-images
          [ -f output/light.svg ] && mv output/light.svg /tmp/breakout-images/breakout-light.svg || echo "light.svg not found"
          [ -f output/dark.svg ] && mv output/dark.svg /tmp/breakout-images/breakout-dark.svg || echo "dark.svg not found"
          [ -f output/custom.svg ] && mv output/custom.svg /tmp/breakout-images/breakout-custom.svg || echo "custom.svg not found"

      - name: Configure git
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      - name: Commit and force-push SVGs to target branch
        run: |
          git checkout --orphan github-breakout
          git rm -rf .
          mkdir images
          mv /tmp/breakout-images/* images/
          git add images
          git commit -m "chore: update GitHub breakout SVGs" || echo "No changes to commit"
          git push --force origin github-breakout
